services:
  api-gateway:
    build:
      context: ./server/api-gateway
      dockerfile: ./Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./server/api-gateway:/app
    env_file:
      - ./server/api-gateway/.env
    networks:
      - app_network
    
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # Configuração do Prometheus
    ports:
      - "9090:9090" # Exponha a interface web do Prometheus
    networks:
      - app_network

  grafana:
    image: grafana/grafana:latest
    ports:
       - "4000:3000" # Exponha na porta 4000
    volumes:
      - grafana_data:/var/lib/grafana # Persistência de dados
    networks:
      - app_network
    environment:
      - GF_LOG_LEVEL=error # Mostra apenas erros

  auth-service:
    build:
      context: ./server/auth-service
      dockerfile: ./Dockerfile
    ports:
      - "3500:3500"
    volumes:
      - ./server/auth-service:/app
    env_file:
      - ./server/auth-service/.env
    networks:
      - app_network

  project-service:
    build:
      context: ./server/project/
      dockerfile: ./Dockerfile
    user: "1000:1000"
    ports:
      - "3002:3002"
    volumes:
      - ./server/project/:/app
    networks:
      - app_network
    environment:
      - NODE_ENV=production

networks:
  app_network:
    driver: bridge

volumes:
  grafana_data:
